
package com.example.soapclient.Service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://tempuri.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://tempuri.org", className = "swa.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://tempuri.org", className = "swa.SayHelloResponse")
    @Action(input = "http://tempuri.org/Hello/sayHelloRequest", output = "http://tempuri.org/Hello/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://tempuri.org", className = "swa.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://tempuri.org", className = "swa.DownloadResponse")
    @Action(input = "http://tempuri.org/Hello/downloadRequest", output = "http://tempuri.org/Hello/downloadResponse")
    public byte[] download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
